use_frameworks!

target 'LocalAuthenticator_Example' do
  pod 'LocalAuthenticator', :path => '../'

  target 'LocalAuthenticator_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
